#  Template .NET Core b#  Template .NET Core build
#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.
# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/
image: mcr.microsoft.com/dotnet/sdk:6.0


pipelines:
  branches:
        master:
            - step:
                  name: "Package"
                  caches:
                      - dotnetcore
                  script:
                      - apt-get update
                      - apt-get install zip -y
                      # Build all from warehouse management
                      - cd lei22_23_s5_3dk_61
                      - dotnet restore
                      - dotnet build
                      # Build all and test tests
                      - cd ..
                      - dotnet restore
                      - dotnet build
                      - dotnet test
                      # Web
#                      - git archive --format=tar.gz master -o application.tar.gz
                      - git archive --format=tar.gz HEAD:lei22_23_s5_3dk_61/ -o application.tar.gz
                  artifacts:
                    - application.tar.gz

#            - step:
 #                 name: Deploy to heroku
#                  deployment: Production
#                  trigger: manual
#                  script:
#                    - cd lei22_23_s5_3dk_61
#                    - git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master#                      - pwd
#                      - ls
#                      - pipe: atlassian/heroku-deploy:2.0.0
#                        variables:
#                            HEROKU_API_KEY: $HEROKU_API_KEY
#                            HEROKU_APP_NAME: $HEROKU_APP_NAME
#                            ZIP_FILE: "application.tar.gz"
 #                           WAIT: 'true'
