@startuml Sequence Diagram
autonumber

actor ADMIN as LM

participant "<<System>> <<Context C4>> ELETRIC GO" as SYS

activate LM
alt if user doesn't exist
LM -> SYS: Starts to get the user
activate SYS 
SYS --> LM: Asks for data
deactivate SYS
LM-> SYS : Introduce the requested data
activate SYS  

alt if ok 


LM <-- SYS: OK shows user
deactivate SYS

LM -> SYS: changes user active 
activate SYS

SYS --> LM: shows user deactivated/occupied
deactivate SYS 


else error 
 

LM <-- SYS: ERROR

deactivate SYS



end alt


deactivate LM
@enduml