@startuml Sequence Diagram
autonumber

actor WAREHOUSEMANAGER as WMR

participant "<<System>> <<Context C4>> ELETRIC GO" as SYS

activate LM
alt if warehouse doesn't exist
LM -> SYS: Starts to get the warehouse
activate SYS 
SYS --> LM: Asks for data
deactivate SYS
LM-> SYS : Introduce the requested data
activate SYS  

alt if ok 


LM <-- SYS: OK shows warehouse
deactivate SYS

LM -> SYS: changes warehouse active 
activate SYS

SYS --> LM: shows warehouse deactivated/occupied
deactivate SYS 


else error 
 

LM <-- SYS: ERROR

deactivate SYS



end alt


deactivate LM
@enduml