@startuml Sequence Diagram
autonumber

actor Router as LM

activate LM
box "<<System>> EletricGO" #LightBlue
'participant "<<System>> EletricGO" as E
participant "Views" as Views
participant "ListWarehouseTS" as ctr
participant "WarehouseService" as serv
end box




            LM -> Views: asks to list the warehouses
            activate Views
            Views -> ctr: getwarehouses()
            deactivate Views
            activate ctr

    ctr -> serv: getwarehouses
    deactivate ctr
    activate serv
   
 

    alt if ok
    

    serv --> Views: 200
     
    activate Views
    LM <-- Views: OK
    deactivate Views

     LM -> Views: asks to change warehouse status
            activate Views

                        alt disable warehouse

            Views -> ctr: changeStatusDisables()
            activate ctr

    ctr -> serv: changeStatusDisables
    deactivate ctr
    serv --> Views: 200
     
    LM <-- Views: OK shows disabled warehouse


               else enables warehouse

  Views -> ctr: changeStatusEnables()
            activate ctr

    ctr -> serv: changeStatusEnables
    deactivate ctr
    serv --> Views: 200
     
    LM <-- Views: OK shows enabled warehouse
    deactivate Views

end alt
    else error
    Views <-- serv: 400/423
    deactivate ctr
    activate Views

    LM <-- Views: ERROR
    deactivate Views

                end alt
               


                deactivate LM

                @enduml